#include<stdio.h>
int main()
{
	int T,x,n,nn,input[10000],forb,i,j;			//n-number of characters to push fwd/bwd,x-ascii val to shift number by
	scanf("%d",&T);
	while(T--)
	{
		scanf("%d%d",&n,&x);
		nn=2*n;
		x%=26;
		for(i=0;scanf("%d",&input[i]);i++)
		{
			if(input[i]==(-1))
				break;
			else
			{
				forb=i%nn;
				if(input[i]>=65&&input[i]<=90)
				{
					if(forb<n)
						input[i]-=x;
					else
						input[i]+=x;
					if(input[i]<65)
						input[i]+=26;
					if(input[i]>90)
						input[i]-=26;
				}
				if(input[i]>=97&&input[i]<=122)
				{
					if(forb<n)
						input[i]-=x;
					else
						input[i]+=x;
					if(input[i]<97)
						input[i]+=26;
					if(input[i]>122)
						input[i]-=26;
				}
			}
		}
		for(j=0;j<i;j++)
			printf("%c",input[j]);
		printf("\n");
	}
	return 0;
}
